### ISSUE TITLE
semi-colon ";" in data: uri will break the unminified CSS

### ISSUE THREAD

**Issue by karlcow** [RoxasShadow/Workspace#1]
This will be unminified with a break after `data:image/png;` and will make the `background-image unusable.`

``` css
.test {color:#000;background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFgAAAA4AgMAAAAED9f9AAAACVBMVEUAAABmZmZmZmaO3ZBrAAAAA3RSTlMA5rA5MyM4AAAAJElEQVQ4y2MYOUA1FAEiEMKiSMIheIUxDRkFo9Ew2MFoeBMDAPLUMTllKtkfAAAAAElFTkSuQmCC);}
```

See https://github.com/RoxasShadow/Workspace/blob/d368ec429a7281e8bd4e302ef0821691d91f60fc/Ruby/unminify.rb
